---
author: Di Shao
categories:
- communication
date: "2019-05-14"
draft: false
excerpt: 使用TidyTuesday数据练习tidyverse
layout: single
subtitle:
title: TidyTuesday学习笔记--Nobel_Laureate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
原视频地址：https://www.bilibili.com/video/BV1P4411m75N?from=search&seid=7741503924513681460&spm_id_from=333.337.0.0


<iframe src="//player.bilibili.com/player.html?aid=66165578&bvid=BV1P4411m75N&cid=114760204&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>
## Load needed packages

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
```

## Get the data!

```{r message=FALSE}
nobel_winners <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv") %>% 
  distinct(full_name, prize_year, category, .keep_all = T) %>% 
  mutate(decade = 10*(prize_year%/%10),
         age = prize_year - year(birth_date))
nobel_winner_all_pubs <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winner_all_pubs.csv") %>% 
  mutate(prize_decade = 10*(prize_year %/% 10))
```

## Winners per decade by category

```{r}
nobel_winners %>% 
  group_by(category,decade) %>%
  summarise(winners = n(),
            winners_per_year = winners / n_distinct(prize_year)) %>% 
  ggplot(aes(decade, winners_per_year, color= category)) + 
  geom_line() +
  expand_limits(y=0)

```

```{r}
nobel_winners %>% 
  group_by(full_name) %>% 
  mutate(prizes = n(),
         distinct_prizes = n_distinct(category)
         ) %>% 
  arrange(desc(prizes), full_name)
```

## Nobel prize gender distribution
```{r}
nobel_winners %>% 
  count(decade,
        category,
        gender = coalesce(gender, laureate_type)) %>% 
  ggplot(aes(decade, n, fill = gender)) +
  geom_col() +
  facet_wrap(~ category) +
  labs(x = "Decade",
       y = "# of nobel prize winners",
       fill = "Gender",
       title ="Nobel prize gender distribution")
  
```

## Nobel prize age distribution
```{r}

nobel_winners %>% 
  mutate(category = fct_reorder(category, age, na.rm = T)) %>% 
  ggplot(aes(category, age)) +
  geom_boxplot() +
  coord_flip()
```

## Trend of winner's age 
```{r}
nobel_winners %>% 
  filter(!is.na(age)) %>% 
  group_by(decade, category) %>% 
  summarise(average_age = mean(age),
            median_age = median(age)) %>% 
  ggplot(aes(decade,average_age, color = category)) +
  geom_line() 
  
```

## Nobel prize country distribution
```{r}
nobel_winners %>% 
  filter(!is.na(birth_country)) %>% 
  count(category, 
        birth_country = fct_lump(birth_country, 9),
        sort = T) %>% 
  ggplot(aes(birth_country, n, fill=category)) +
  geom_col() +
  facet_wrap(~ category) +
  coord_flip()
```


```{r}
winner_summarized <- nobel_winner_all_pubs %>% 
  filter(pub_year <= prize_year) %>% 
  group_by(laureate_id,
           laureate_name,
           prize_year,
           category,
           prize_decade) %>% 
  summarise(paper_before_prize = n(),
            paper_before_prize_5_years = sum(pub_year >= prize_year -5),
            median_paper_age = median(prize_year - pub_year),
            winning_paper_age = mean((prize_year - pub_year)[is_prize_winning_paper == "YES"])) 

```

## Time between when paper was published and won prize
```{r}
winner_summarized %>% 
  group_by(prize_decade,
           category) %>% 
  summarize(average_papers = mean(paper_before_prize),
            average_paper_age = mean(median_paper_age),
            average_winning_paper_age = mean(winning_paper_age)) %>% 
  ggplot(aes(prize_decade,average_winning_paper_age, color = category )) +
  geom_line() +
  labs(x = "Prize Year",
       y = "Time between when paper was published and won prize") +
  expand_limits(y = 0)
```

## positon_in_career when getting the prize
```{r}
pubs_enriched <- nobel_winner_all_pubs %>% 
  group_by(laureate_id, category, prize_year) %>% 
  mutate(paper_before = rank(pub_year, ties.method = "first") - 1,
         total_paper = n(),
         position_in_career = paper_before / total_paper,
         first_pub_year = min(pub_year)) %>% 
  ungroup()


pubs_enriched %>% 
  filter(is_prize_winning_paper == "YES") %>% 
  group_by(prize_decade, category) %>% 
  summarize(average_positon_in_career = mean(position_in_career)) %>% 
  ggplot(aes(prize_decade, average_positon_in_career)) +
  geom_line(aes(color = category)) +
  scale_y_continuous(labels = scales::percent_format())
  
```

## positon in their publishing career
```{r}
pubs_enriched %>% 
  filter(pub_year - first_pub_year < 75,
         prize_year >= 1900,
         prize_year <= 2000) %>%
  ggplot(aes(pub_year - first_pub_year, fill = is_prize_winning_paper)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ category)  +
  labs(x = "Years into their publishing career")
  
```
